services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5440:5432'
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
